name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}

      - name: 📦 Create deployment artifact
        run: |
          zip -r deploy.zip . -x ".*" -x "deploy.zip"
        
  
      - name: 💾 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-artifact
          path: deploy.zip